export const correctUserKeys = [
    'userType',
    'isPayingMember',
    '_id',
    'username',
    'timezone',
    'coins',
    'oidXp',
    'totalLiveStreaks',
    'profileImages',
    'achievements',
    'followers',
    'following',
    'totalStreakCompletes',
    'createdAt',
    'updatedAt',
].sort();
