export const correctCurrentUserPopulatedTeamStreakKeys = [
    '_id',
    'status',
    'currentStreak',
    'completedToday',
    'active',
    'pastStreaks',
    'streakName',
    'timezone',
    'creator',
    'creatorId',
    'members',
    'createdAt',
    'updatedAt',
    'totalTimesTracked',
    'inviteKey',
    '__v',
].sort();
