export const correctSoloStreakKeys = [
    '_id',
    'status',
    'currentStreak',
    'completedToday',
    'active',
    'pastStreaks',
    'streakName',
    'streakDescription',
    'userId',
    'timezone',
    'totalTimesTracked',
    'longestSoloStreak',
    'createdAt',
    'updatedAt',
    '__v',
].sort();
