export const correctTeamMemberStreakKeys = [
    '_id',
    'currentStreak',
    'completedToday',
    'status',
    'active',
    'pastStreaks',
    'userId',
    'teamStreakId',
    'totalTimesTracked',
    'longestTeamMemberStreak',
    'timezone',
    'streakType',
    'createdAt',
    'updatedAt',
    '__v',
].sort();
