export enum Collections {
    Users = 'Users',
    Feedback = 'Feedback',
    StripeCustomers = 'StripeCustomers',
    SoloStreaks = 'SoloStreaks',
    TeamStreaks = 'TeamStreaks',
    AgendaJobs = 'AgendaJobs',
    CompleteSoloStreakTasks = 'CompleteSoloStreakTasks',
    IncompleteSoloStreakTasks = 'IncompleteSoloStreakTasks',
    CompleteTeamMemberStreakTasks = 'CompleteTeamMemberStreakTasks',
    IncompleteTeamMemberStreakTasks = 'IncompleteTeamMemberStreakTasks',
    CompleteTeamStreakTasks = 'CompleteTeamStreakTasks',
    System = 'System',
    StreakTrackingEvents = 'StreakTrackingEvents',
    TeamMemberStreaks = 'TeamMemberStreaks',
    FriendRequests = 'FriendRequests',
    DailyJobs = 'DailyJobs',
}
