export enum Models {
    User = 'User',
    Feedback = 'Feedback',
    SoloStreak = 'SoloStreak',
    AgendaJob = 'AgendaJob',
    CompleteSoloStreakTask = 'CompleteSoloStreakTask',
    IncompleteSoloStreakTask = 'IncompleteSoloStreakTask',
    CompleteTeamMemberStreakTask = 'CompleteTeamMemberStreakTask',
    IncompleteTeamMemberStreakTask = 'IncompleteTeamMemberStreakTask',
    CompleteTeamStreak = 'CompleteTeamStreak',
    IncompleteTeamStreak = 'IncompleteTeamStreak',
    TeamStreak = 'TeamStreak',
    StreakTrackingEvent = 'StreakTrackingEvent',
    TeamMemberStreak = 'TeamMemberStreak',
    FriendRequest = 'FriendRequest',
    DailyJob = 'DailyJob',
    Email = 'Email',
}
