export enum Models {
    User = 'User',
    Feedback = 'Feedback',
    SoloStreak = 'SoloStreak',
    AgendaJob = 'AgendaJob',
    CompleteSoloStreakTask = 'CompleteSoloStreakTask',
    IncompleteSoloStreakTask = 'IncompleteSoloStreakTask',
    CompleteGroupMemberStreakTask = 'CompleteGroupMemberStreakTask',
    IncompleteGroupMemberStreakTask = 'IncompleteGroupMemberStreakTask',
    CompleteTeamStreakTask = 'CompleteTeamStreakTask',
    TeamStreak = 'TeamStreak',
    StreakTrackingEvent = 'StreakTrackingEvent',
    GroupMemberStreak = 'GroupMemberStreak',
    FriendRequest = 'FriendRequest',
    DailyJob = 'DailyJob',
}
